### ISSUE TITLE
date_from not present in restriction_header_date table

### ISSUE THREAD

**Issue by eoghanmurray** [open-track/fares-engine#1]
I'm getting the following error after `npm start`:
```

{ Error: ER_BAD_FIELD_ERROR: Unknown column 'start_date' in 'order clause'
    at RestrictionRepository.getRestrictionHeaderDates (/home/eoghan/projects/fares-engine/src/restriction/repository/RestrictionRepository.ts:46:8)
    at RestrictionRepository.createRestriction (/home/eoghan/projects/fares-engine/src/restriction/repository/RestrictionRepository.ts:36:12)
  code: 'ER_BAD_FIELD_ERROR',
  errno: 1054,
  sqlMessage: 'Unknown column \'start_date\' in \'order clause\'',
  sqlState: '42S22',
  index: 0,
  sql: 'SELECT * FROM restriction_header_date WHERE restriction_code = \'1A\' ORDER BY start_date' }

```

The corresponding column in the database (after running the dtd2mysql project directly) is `date_from` which is `char(4)`.  I've tried a simple rename but ran into the following:

```
{ NullPointerException
    at createRestrictionDate (/home/eoghan/projects/fares-engine/src/restriction/repository/RestrictionRepository.ts:115:17)
    at runCallback (timers.js:781:20) message: 'text must not be null' }
(node:19043) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: Cannot read property 'start' of undefined
(node:19043) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

```

So I figure maybe I'm missing a step where the 4-character date is converted to a proper MySql `date` type?

**Comment by eoghanmurray** [comment]
Aha got it:

https://github.com/open-track/dtd2mysql

Clean

... adds full date entries to restriction date records...
